services:
  mcs:
    container_name: mcs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MCS_ROOT_PASSWORD:-C0lumnStore!}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./volumes/db:/var/lib/mysql:Z
    ports:
      - 3306:3306

