services:
  mcs:
    container_name: ${MCS:-mcs}
    hostname: ${MCS:-mcs}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    shm_size: '512MB'
    ulimits:
      core: 0
    environment:
      - TZ=UTC
      - PM1=${MCS:-mcs}
      - MARIADB_ROOT_PASSWORD=${MCS_ROOT_PASSWORD:-C0lumnStore!}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - mcs_mysql_config:/etc/mysql
      - mcs_mysql_data:/var/lib/mysql
      - mcs_columnstore_config:/etc/columnstore
      - mcs_columnstore_data:/var/lib/columnstore
    ports:
      - 3306:3306

volumes:
  mcs_mysql_config:
  mcs_mysql_data:
  mcs_columnstore_config:
  mcs_columnstore_data:

